import { NextPage } from 'next';
import styled from 'styled-components';

const Container = styled.div`
  padding: 0 2rem;
`;

const Main = styled.main`
  min-height: 100vh;
  padding: 4rem 0;
  flex: 1;
  display: flex;
  flex-direction: column;
  justify-content: center;
  align-items: center;
`;

const Title = styled.h1`
  margin: 0;
  line-height: 1.15;
  font-size: 4rem;
  text-align: center;

  a {
    color: #ccc002;
    text-decoration: none;

    &:hover,
    &:focus,
    &:active {
      text-decoration: underline;
    }
  }
`;

// Continue with other styled components...

const MshrsAgreement: NextPage = () => {
  return (
    <Container>
      <Main>
        <Title>
          <a href="#">M
            <a href="#">SHRS </a>
          </a>
        </Title>

        <div>
          <h2>Music Shares Agreement</h2>
          <p>
          This NFT Contract (the "Contract") is entered into by and between MEMAKYOU (the "Artist") and the holder of the NFT token (the "Buyer"). SRSLYRARE LLC (the "Facilitator") is facilitating the transaction on behalf of the Artist.
          </p>
          <p>
          For the purposes of this Contract, "Mechanical Royalties" shall mean the royalties payable to the Artist for the reproduction and distribution of the Artist's copyrighted musical compositions through various formats such as physical copies, downloads, and streaming services.
          </p>
          <p>
          Metadata:
The following metadata is associated with each unique NFT token being sold in this contract:
          </p>
         
          <ul>
            <li>Token Name: MUSIC SHARES</li>
            <li>Token Symbol: $MSHRS</li>
            <li>Total Supply: 100,000 (per song)</li>
            <li>Contract Address: [INSERT CONTRACT ADDRESS]</li>
            <li>Blockchain Network: Polygon</li>
            <li>Artist: MEMAKYOU</li>
            <li>Royalty Percentage: 20% per song (each token represents 0.0002% of the royalties)</li>
          </ul>
          <p>The following metadata will be provided upon the release of a new token ID and attached to the 1155 token for each unique NFT token being sold in this contract.</p>
        
          <ul>
            <li>Song Title:</li>
            <li>Release Date:</li>
            <li>ISRC Code:</li>
            <li>Writer(s):</li>
            <li>Publisher:</li>
            <li>Label:</li>
            <li>Genre:</li>
            <li>Duration:</li>
          </ul>

            <p>
            The above metadata is intended to provide additional information about the unique NFT token(s) being sold in this contract and is not intended to modify or replace any of the terms and conditions set forth in the contract.
            </p>
            <p>
            Sale of Mechanical Royalties. For each song released by the Artist on Spotify, the Artist agrees to sell and transfer 20% of the mechanical royalties generated by the song through the sale of 100,000 $MSHRS NFT tokens, each token representing 0.0002% ownership in the mechanical royalties. The Facilitator, an independent body working to support independent arts, will facilitate the transaction of these royalties on behalf of the Artist. Their responsibility in this process is limited to facilitating the transaction of mechanical royalties between the Artist and the Buyer.
            </p>
            <p>
            Rights of the Buyer. Upon purchasing the NFT tokens, the Buyer will receive the right to receive a percentage of the mechanical royalties generated by the selected song. The Buyer will be paid quarterly within 60 days after the end of each calendar quarter. The Facilitator shall provide the Buyer with a detailed royalty statement, reflecting the calculations of the royalties earned, within 60 days after the end of each calendar quarter. The royalty statement will be issued via a gated portal on the MEMAKYOU app.
            </p>
            <p>
            Purchase Price and Royalty Distribution. The purchase price for each NFT token is 6 EUR. The royalties will be collected by the Facilitator on behalf of the Artist four times annually and distributed to the Buyer in proportion to their ownership percentage represented by the NFT tokens through the Music Shares Portal, a tool within the MEMAKYOU app. The Buyer acknowledges that they are responsible for any taxes or other fees related to the purchase or sale of the NFT tokens.
            </p>
            <p>
            Terms of Sale. The sale is considered final upon minting of the NFT tokens, and no refunds will be issued. The NFT tokens can be resold on any marketplace desired by the owner, subject to any conditions or limitations specified in the NFT Contract. The Artist may not repurchase the NFT tokens from the Buyer unless both parties agree in writing to a buyback agreement.
            </p>
            <p>Responsibilities and Liabilities. Both the Buyer and the Artist agree to fulfill their respective obligations as set forth in the NFT Contract. Any disputes related to this contract will be resolved through arbitration in accordance with the rules of The Chartered Institute of Arbitrators in Ireland, with the arbitration to be held in Dublin, Republic of Ireland on an ad hoc basis. The prevailing party in any arbitration or legal proceeding related to this contract will be entitled to recover its reasonable attorneys' fees and costs.</p>
            <p>
            Disclaimers and Limitations of Liability. The Buyer acknowledges that owning an NFT token grants them the right to use the underlying artwork for personal, non-commercial use only. Any commercial use of the underlying artwork without the express written consent of the Artist is strictly prohibited.  
            </p>
            <p>
            Additionally, the Artist and the Facilitator will not be liable for any damages or losses suffered by the Buyer as a result of the sale of the NFT tokens, including but not limited to lost profits or lost opportunities. The parties are not responsible for downtime or issues related to the Polygon network. The Buyer's rights and obligations related to the NFT tokens are subject to any applicable laws and regulations, including anti-money laundering and counter-terrorism financing regulations.
            </p>
            <p>
            Governing Law. This Contract will be governed by and construed in accordance with the laws of the Republic of Ireland, without regard to its conflict of law provisions.
            </p>
            <p>
            Termination and Modification. This Contract may be terminated by either party upon written notice to the other party if a force majeure event occurs. A force majeure event is defined as any event beyond the reasonable control of either party, including but not limited to acts of God, war, terrorism, civil unrest, or failure of communication systems.
            </p>
            <p>
            Assignment. Neither party may assign its rights or obligations under this Contract without the prior written consent of the other party, except that the Artist may assign its rights and obligations to an affiliate or successor in interest without the consent of the Buyer, provided that such assignment does not materially affect the Buyer's rights or obligations under this Contract.
            </p>
            <p>
            Severability. If any provision of this Contract is held to be invalid, illegal, or unenforceable by a court of competent jurisdiction, the remaining provisions of this Contract shall remain in full force and effect, and the invalid, illegal, or unenforceable provision shall be deemed modified to the minimum extent necessary to render it valid, legal, and enforceable."
Remember to consult with legal counsel to ensure that the revised contract meets the specific needs of both parties and complies with applicable laws and regulations.
            </p>
            <p>
            Representations and Warranties. Both parties represent and warrant that they have the authority to enter into this Contract and that they will not breach any other agreements, covenants, or obligations in doing so. The Artist represents and warrants that they have the right to sell the mechanical royalties and that the Buyer will not be subject to any claims or encumbrances related to the mechanical royalties. Additionally, the Artist represents and warrants that they have the right to use any underlying artwork or other intellectual property associated with the NFT.
            </p>
            <p>
            Miscellaneous. This Contract constitutes the entire agreement between the parties concerning the subject matter hereof, and supersedes all prior and contemporaneous agreements, whether oral or written, between the parties relating thereto. No amendment, modification, or waiver of any provision of this Contract shall be effective unless in writing and signed by both parties. If any provision of this Contract is held to be invalid, illegal, or unenforceable, the remaining provisions shall remain in full force and effect.
            </p>
            <p>
            IN WITNESS WHEREOF, the parties have executed this Contract as of the date first above written.
            </p>
            <p>
            ARTIST: MEMAKYOU<br/>
            BUYER: [BUYER'S WALLET ADDRESS]<br/>
            FACILITATOR: SRSLYRARE LLC<br/>
            </p>
      </div>
      </Main>
    </Container>
  );
};

export default MshrsAgreement;